//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazinOnline.Models.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        public int ID { get; set; }
        public string Denumire { get; set; }
        public string Descriere { get; set; }
        public double Pret { get; set; }
        public int Stoc { get; set; }
        public Nullable<int> ID_Furnizor { get; set; }
        public Nullable<int> ID_Categorie { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Furnizor Furnizor { get; set; }
    }
}
